### ISSUE TITLE
No event triggered in absolute position

### ISSUE THREAD

**Issue by yairopro** [mlisook/resize-aware#6]
Hello
When I set the `resize-aware` in `position: absolute` in order to make it fit the parent dimensions, it doesn't trigger any event when resizing the window. It triggers twice only while the document is constructing.

Here's a live exemple [on Plunker](http://plnkr.co/edit/AtSKbTkoGm0dr2lARWNN?p=preview) (I've copied-paste your resize-aware module). You'll be able to resize the document via Plunker's window. Check the console to see if the event is trigger, it should display `resized` each time the event is triggered.

**Comment by mlisook** [comment]
Thank you for reporting this and for the excellent example.  I'll work on it straight away.

I must admit I've never tried positioning the `resize-aware` element itself, not to imply that should not be supported. I have absolute positioned the element containing `resize-aware`, for example in `plastic-map-info`, where I need to move the infoWindow if the size of the content changes to keep it above the map marker.

**Comment by yairopro** [comment]
Thanks a lot for working on it.
PS: I wanted to thank you a lot for your work. I'm really fond of some of your components. =D

**Comment by mlisook** [comment]
I apologize for the delay.  I'm traveling in rural areas in the US, many of which do not have usable network coverage available.

I have not been able to figure out how to get an absolute positioned `resize-aware` to work.  The method of size change is dependent on detecting scroll of the content inside.

Perhaps you can provide a little more information on the context of what you are trying to achieve with the container and I may be able to figure out an alternate way to use the element.

**Comment by mlisook** [comment]
I just found some code I used in an app I did for a client that could potentially be pertinent.

In that case I changed the font size of an absolutely positioned element that overlayed a picture with a title.  Below is a trimmed down version of that code:
```html
<plastic-aspect-ratio aspect-width="4" aspect-height="3" style="width:100%;">
    <plastic-image id="i50a" use-element-dim lazy-load preload fade placeholder="data: image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD//gA7Q1JFQVRPUjogZ2QtanBlZyB2MS4wICh1c2luZyBJSkcgSlBFRyB2OTApLCBxdWFsaXR5ID0gODIK/9sAQwAGBAQFBAQGBQUFBgYGBwkOCQkICAkSDQ0KDhUSFhYVEhQUFxohHBcYHxkUFB0nHR8iIyUlJRYcKSwoJCshJCUk/9sAQwEGBgYJCAkRCQkRJBgUGCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQk/8AAEQgACwAOAwEiAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/aAAwDAQACEQMRAD8Aq6FfQ+F7JLPUYLG/uYRgSrbsjFTzjJYZI75H51R1j4qiG8WHTdJsJEMYc/JI5Gfow9+Pauz8X+GdJl8LWUjWn7yARhJBI4flTnLA5boOuelcvoOi6dq/h22uLuzhM4CqZYx5TP8AL/EUwW6Dk5pQzOtGCjF2KlgqTk21qf/Z"
                sizing="cover" srcset="images/IMG_20170425_111558-150x150.jpg 150w, images/IMG_20170425_111558-300x225.jpg 300w, images/IMG_20170425_111558-768x576.jpg 768w"
                style="height: 100%; width: 100%;">
    </plastic-image>
    <div style="position:absolute; box-sizing:border-box; top:5px;right:0px; width:100%;">
      <resize-aware id="ra2">
            <div id="titleOverlay" style="box-sizing:border-box; padding-left:3%;width:100%;color:white; font-size:16px; font-weight:bold;">Grand Canyon, AZ</div>
      </resize-aware>
    </div>
</plastic-aspect-ratio>
```
```javascript
document.querySelector('#ra2').addEventListener('element-resize', function (e) {
     let titleOverlay = document.querySelector('#titleOverlay');
     titleOverlay.style.fontSize = Math.floor(e.detail.width/16) + "px";
});
```
This does indeed work - firing an event and changing font size as the element size changes. 

`plastic-aspect-ratio` is not really required for this, it was just a technique used to preserve the native aspect ratio of the photo.

**Comment by yairopro** [comment]
Using the `addEventListener` method rather than the attribute `on-element-size-changed` [doesn't seem to help](http://plnkr.co/edit/MWyJUBbu78TKXENC8B9L?p=preview).

But I noticed on the original [Plunk](http://plnkr.co/edit/AtSKbTkoGm0dr2lARWNN?p=preview) that the event is well triggered but **only when the element's size grows**.

**Comment by yairopro** [comment]
It seems that even if the `resize-aware` isn't in `position: absolute` it doesn't trigger an event when its size shrinks. See on this [Plunker](http://plnkr.co/edit/qI1ViE0mNQUFYqZTzCzY?p=preview)

**Comment by mlisook** [comment]
Please see [this fork of your plunker](http://plnkr.co/edit/SPOs0A2jXEIg5u7LeN04?p=preview)

**Comment by yairopro** [comment]
At first glance, it seems work perfectly on your fork. And there's no need to remove `height: 100%` and `width: 100%`.
But even so, you will be able to see on [this plunk](http://plnkr.co/edit/9JAop2ErpF8Ta0QRqoA1?p=preview) that it doesn't trigger when its height changes (try by resizing the window).

**Comment by mlisook** [comment]
Your plunk does not match the content height - see [this plunk](http://plnkr.co/edit/sQ9n2n6xyYLr6a35CMVc?p=preview).

**Comment by yairopro** [comment]
Ah ok. I think I understand. The `resize-aware` element is "aware" of **changes of the sizes of its child**, but not of its own sizes.  Isn't it?

**Comment by mlisook** [comment]
In essence that is true.  It is really detecting horizontal and vertical scroll changes triggered when the child nodes get repainted by a layout change. When a scroll occurs it measures itself and includes the measurement in the event.

**Comment by yairopro** [comment]
Then that's why it wasn't triggering the event in the original Plunk of this issue. Because there was no children in it.
Then maybe you should change the component description.
